import { upsertRegion, getRegionBySlug } from '../queries/region'
import { upsertPatient } from '../queries/patient'
import regionsData from './data/regions.json'
import patientsData from './data/patients.json'

async function seed() {
  // Map to store slug to region id
  const slugToId = new Map<string, string>()

  // Insert regions in order: KABUPATEN, KECAMATAN, DESA
  for (const type of ['KABUPATEN', 'KECAMATAN', 'DESA'] as const) {
    for (const region of regionsData.filter((r) => r.type === type)) {
      let parentId: string | undefined = undefined
      if (region.parentSlug) {
        const parentRegion = await getRegionBySlug(region.parentSlug)
        if (!parentRegion) {
          throw new Error(
            `Parent region with slug '${region.parentSlug}' not found for region '${region.slug}'`
          )
        }
        parentId = parentRegion.id
      }
      const dbRegion = await upsertRegion({
        name: region.name,
        slug: region.slug,
        type: region.type as 'KABUPATEN' | 'KECAMATAN' | 'DESA',
        parentId: parentId ?? null
      })
      if (dbRegion && dbRegion.id) {
        slugToId.set(region.slug, dbRegion.id)
      }
    }
  }

  // Seed patients for each DESA from patients.json
  for (const patient of patientsData) {
    const regionId = slugToId.get(patient.regionSlug)
    if (!regionId) {
      throw new Error(
        `Region ID not found for slug '${patient.regionSlug}' in patient '${patient.name}'`
      )
    }
    await upsertPatient({
      name: patient.name,
      motherName: patient.motherName,
      birthDate: new Date(patient.birthDate),
      status: patient.status as 'HAMIL' | 'MENYUSUI' | 'ANAK-ANAK',
      location: patient.location,
      regionId,
      initialWeight: patient.initialWeight,
      initialHeight: patient.initialHeight
      // Do not pass slug, let it be autogenerated
    })
  }

  console.log('Seed completed!')
}

seed()
  .then(() => {
    process.exit(0)
  })
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
