services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: 'mysql://test:test@db:3306/test'
      # DB_DEBUG: true
    ports:
      - '4321:4321'
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:10.11.10
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.2
    environment:
      PMA_HOST: db
      PMA_USER: test
      PMA_PASSWORD: test
    ports:
      - '4322:80'
    depends_on:
      - db

volumes:
  db_data:
