services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: 'mysql://test:test@db:3306/test'
      DB_DEBUG: true
    ports:
      - '4321:4321'
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:10.11.13@sha256:34adebbac117c8ce649040e009f520fb79e577c68cc4e57debdf91befa53907f
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.2@sha256:73467128842bc4406372310f068bc9ccb6727a82c7b5dc9c4f3d815ead33eab8
    environment:
      PMA_HOST: db
      PMA_USER: test
      PMA_PASSWORD: test
    ports:
      - '4322:80'
    depends_on:
      - db

volumes:
  db_data:
