/**
 * @fileoverview SILARAS PWA Service Worker
 *
 * Comprehensive Progressive Web App service worker for the SILARAS nutrition monitoring system.
 * Implements multi-strategy caching, offline capabilities, and background sync for optimal
 * field worker experience in remote areas with limited connectivity.
 *
 * @features
 * - Static asset precaching with automatic cleanup
 * - Multi-strategy caching (Cache First, Network First, Stale-While-Revalidate, Network Only)
 * - Background sync for failed API requests
 * - Offline fallback handling
 * - Real-time client communication
 * - Cache management and invalidation
 *
 * @caching-strategies
 * - **Cache First**: Static assets (fonts, images, _astro files) - 1 year retention
 * - **Network First**: API endpoints with 3s timeout and background sync - 24 hours retention
 * - **Stale While Revalidate**: Regional data - 12 hours retention
 * - **Network Only**: Authentication and health check endpoints
 *
 * @offline-support
 * - Automatic assessment queuing when offline
 * - Background sync when connection restored
 * - Cached page serving with fallback
 * - IndexedDB integration for persistent storage
 *
 * @author SNGR Creative
 * @version 1.0.0
 * @since 2024
 * @license MIT
 */

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import {
  CacheFirst,
  NetworkFirst,
  StaleWhileRevalidate,
  NetworkOnly
} from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'
import { BackgroundSyncPlugin } from 'workbox-background-sync'

// Type fixes for workbox plugins compatibility
type WorkboxPlugin = any

declare let self: ServiceWorkerGlobalScope

/**
 * ==========================================
 * PRECACHING SETUP
 * ==========================================
 * Precache all static assets generated by Astro build process
 * and clean up outdated caches from previous versions
 */

// Precache static assets generated by Astro
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

/**
 * ==========================================
 * CACHING STRATEGIES
 * ==========================================
 * Multiple caching strategies optimized for different content types
 * to provide the best balance of performance and freshness
 */

/**
 * CACHE FIRST STRATEGY - Static Assets
 *
 * For assets that rarely change and are hashed (fonts, images, CSS, JS from _astro folder).
 * These assets have long cache times since they're versioned by hash.
 *
 * Cache: static-assets
 * Retention: 1 year (365 days)
 * Max Entries: 100
 */
registerRoute(
  ({ request, url }) => {
    // Cache fonts, images, CSS, JS from _astro folder (hashed assets)
    return (
      url.pathname.startsWith('/_astro/') ||
      request.destination === 'font' ||
      request.destination === 'image'
    )
  },
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }) as WorkboxPlugin,
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year for hashed assets
      }) as WorkboxPlugin
    ]
  })
)

/**
 * NETWORK FIRST STRATEGY - API Endpoints
 *
 * For dynamic API data that needs to be fresh but should have offline fallback.
 * Includes Astro Actions and API endpoints with background sync for failed requests.
 *
 * Cache: api-cache
 * Timeout: 3 seconds
 * Retention: 24 hours
 * Max Entries: 200
 * Background Sync: 24 hours
 */
registerRoute(
  ({ url }) => {
    // Match Astro Actions and API endpoints
    return (
      url.pathname.startsWith('/_actions/') ||
      url.pathname.startsWith('/api/') ||
      url.pathname === '/healthcheck'
    )
  },
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }) as WorkboxPlugin,
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 // 24 hours
      }) as WorkboxPlugin,
      new BackgroundSyncPlugin('api-queue', {
        maxRetentionTime: 24 * 60 // 24 hours
      }) as WorkboxPlugin
    ]
  })
)

/**
 * STALE WHILE REVALIDATE STRATEGY - Regional Data
 *
 * For regional and target data that can be slightly stale for better performance.
 * Serves cached content immediately while updating in background.
 *
 * Cache: regional-data
 * Retention: 12 hours
 * Max Entries: 100
 */
registerRoute(
  ({ url }) => {
    // Match region and target pages/data
    return (
      url.pathname.startsWith('/region/') || url.pathname.startsWith('/target/')
    )
  },
  new StaleWhileRevalidate({
    cacheName: 'regional-data',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }) as WorkboxPlugin,
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 12 // 12 hours
      }) as WorkboxPlugin
    ]
  })
)

/**
 * NETWORK FIRST STRATEGY - Assessment Data
 *
 * For dynamic assessment and menu data with shorter cache time.
 * Prioritizes fresh data but provides offline fallback.
 *
 * Cache: assessment-data
 * Timeout: 2 seconds
 * Retention: 30 minutes
 * Max Entries: 50
 */
registerRoute(
  ({ url }) => {
    return (
      url.pathname.includes('/assessment') || url.pathname.includes('/menu')
    )
  },
  new NetworkFirst({
    cacheName: 'assessment-data',
    networkTimeoutSeconds: 2,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }) as WorkboxPlugin,
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 30 // 30 minutes
      }) as WorkboxPlugin
    ]
  })
)

/**
 * NETWORK ONLY STRATEGY - Real-time Endpoints
 *
 * For endpoints that must always be fresh and should never be cached.
 * Includes authentication, health checks, and real-time status endpoints.
 */
registerRoute(({ url }) => {
  return (
    url.pathname === '/healthcheck' ||
    url.pathname.includes('/logout') ||
    url.pathname.includes('/login')
  )
}, new NetworkOnly())

/**
 * ==========================================
 * BACKGROUND SYNC
 * ==========================================
 * Handle background synchronization for failed API requests
 */

/**
 * Background Sync Event Handler
 *
 * Triggered when network connection is restored after being offline.
 * Processes queued API requests that failed due to network issues.
 *
 * @param {ExtendableEvent} event - The sync event
 */
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'api-queue') {
    event.waitUntil(
      (async () => {
        try {
          // Notify clients about sync attempt
          const clients = await self.clients.matchAll()
          clients.forEach((client: any) => {
            client.postMessage({
              type: 'BACKGROUND_SYNC',
              status: 'attempting'
            })
          })
        } catch (error) {
          console.error('Background sync failed:', error)
        }
      })()
    )
  }
})

/**
 * ==========================================
 * CLIENT COMMUNICATION
 * ==========================================
 * Handle messages from client applications for real-time updates
 */

/**
 * Message Event Handler
 *
 * Processes messages from client applications to control service worker behavior.
 * Supports cache invalidation, refresh commands, and service worker updates.
 *
 * @param {MessageEvent} event - The message event from client
 */
self.addEventListener('message', (event: any) => {
  if (event.data && event.data.type) {
    switch (event.data.type) {
      case 'SKIP_WAITING':
        self.skipWaiting()
        break
      case 'CACHE_INVALIDATE':
        // Clear specific cache
        if (event.data.cacheName) {
          caches.delete(event.data.cacheName)
        }
        break
      case 'CACHE_REFRESH':
        // Force refresh of critical data
        refreshCriticalData()
        break
    }
  }
})

/**
 * ==========================================
 * NETWORK STATUS HANDLING
 * ==========================================
 * Handle online/offline status changes and trigger sync
 */

/**
 * Online Event Handler
 *
 * Triggered when the service worker detects network connectivity is restored.
 * Automatically triggers background sync to process queued requests.
 */
self.addEventListener('online', () => {
  // Force sync when back online
  self.registration.sync.register('api-queue')
})

/**
 * ==========================================
 * SERVICE WORKER LIFECYCLE
 * ==========================================
 * Handle installation, activation, and updates
 */

/**
 * Install Event Handler
 *
 * Triggered when a new service worker is installed.
 * Skips waiting to take control immediately.
 */
self.addEventListener('install', (_event) => {
  self.skipWaiting()
})

/**
 * Activate Event Handler
 *
 * Triggered when the service worker becomes active.
 * Claims all clients and notifies them of activation.
 *
 * @param {ExtendableEvent} event - The activate event
 */

self.addEventListener('activate', (event: any) => {
  event.waitUntil(
    (async () => {
      await self.clients.claim()
      // Notify all clients of activation
      const clients = await self.clients.matchAll()
      clients.forEach((client: any) => {
        client.postMessage({
          type: 'SW_ACTIVATED',
          timestamp: Date.now()
        })
      })
    })()
  )
})

/**
 * ==========================================
 * NAVIGATION HANDLING
 * ==========================================
 * Handle navigation requests and offline fallbacks
 */

/**
 * Navigation Route Configuration
 *
 * Handles navigation requests with network-first strategy and offline fallback.
 * Excludes API routes and static assets from navigation handling.
 *
 * Cache: navigation-cache
 * Timeout: 3 seconds
 * Allowlist: All routes except _actions, api, healthcheck
 * Denylist: _astro static assets
 */
const navigationRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: 'navigation-cache',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200]
      }) as WorkboxPlugin
    ]
  }),
  {
    allowlist: [/^\/(?!_actions|api|healthcheck)/],
    denylist: [/\/_astro\//]
  }
)

registerRoute(navigationRoute)

/**
 * Offline Fallback Route Handler
 *
 * Provides fallback handling for navigation requests when offline.
 * Attempts to serve cached content or offline page as last resort.
 *
 * @param {RouteHandlerCallbackOptions} options - Route handler options
 * @returns {Promise<Response>} The response (cached page or offline fallback)
 */
registerRoute(
  ({ request }) => request.mode === 'navigate',
  async ({ request }) => {
    try {
      const response = await fetch(request)
      return response
    } catch (error) {
      // If navigation fails and we're offline, try to serve cached page
      const cache = await caches.open('navigation-cache')
      const cachedResponse = await cache.match(request)

      if (cachedResponse) {
        return cachedResponse
      }

      // Last resort: serve offline page
      const offlineResponse = await caches.match('/offline')
      return (
        offlineResponse ||
        new Response('Offline', {
          status: 503,
          statusText: 'Service Unavailable'
        })
      )
    }
  }
)

/**
 * ==========================================
 * UTILITY FUNCTIONS
 * ==========================================
 * Helper functions for cache management and data refresh
 */

/**
 * Refresh Critical Data
 *
 * Clears and refreshes critical application caches to ensure fresh data.
 * Notifies all connected clients when refresh is complete.
 *
 * Used when:
 * - Manual cache refresh requested
 * - Critical data needs immediate update
 * - Cache invalidation required
 *
 * @async
 * @function refreshCriticalData
 * @returns {Promise<void>}
 */
async function refreshCriticalData() {
  try {
    // Clear and refetch critical caches
    await caches.delete('api-cache')
    await caches.delete('regional-data')

    // Notify clients
    const clients = await self.clients.matchAll()
    clients.forEach((client: any) => {
      client.postMessage({
        type: 'CACHE_REFRESHED',
        timestamp: Date.now()
      })
    })
  } catch (error) {
    console.error('Failed to refresh critical data:', error)
  }
}
