services:
  db:
    name: Database (MariaDB & PHPMyAdmin)
    commands:
      start: docker compose up phpmyadmin
      stop: docker compose stop phpmyadmin
    triggeredBy:
      - postEnvironmentStart

  minio:
    name: Storage (MinIO)
    commands:
      start: docker compose up minio
      stop: docker compose stop minio
    triggeredBy:
      - postEnvironmentStart

  server:
    name: Astro Dev Server
    commands:
      start: bun run dev --host=0.0.0.0
    triggeredBy:
      - manual

  studio:
    name: Drizzle Studio
    commands:
      start: bun db:studio
    triggeredBy:
      - manual

tasks:
  db-reset:
    name: Reset DB
    command: docker compose down phpmyadmin db --volumes
    triggeredBy:
      - manual

  db-generate:
    name: Generate DB migrations
    command: bun db:generate
    triggeredBy:
      - manual

  db-migrate:
    name: Run DB migration
    command: bun db:migrate
    triggeredBy:
      - manual

  db-seed:
    name: Run DB Seed
    command: bun db:seed
    triggeredBy:
      - manual

  format:
    name: Run Formatter
    command: bun format
    triggeredBy:
      - manual
